name: Auto-Close PRs
on:
  pull_request:
    types: [opened]

jobs:
  closePR:
    runs-on: ubuntu-latest
    steps:
      - name: Post Comment
        run: gh pr comment ${{ github.event.pull_request.html_url }} --body "This repository does not accept pull requests. You should fork and push on your own repository. Your PR has been closed automatically."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
      - name: Close PR
        run: gh pr close ${{ github.event.pull_request.html_url }} -r "PRs not allowed & closed"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Delete Branch
        if: github.event.pull_request.head.repo.full_name == github.repository  # Ensures only branches from the same repo are deleted, not forks
        run: gh api -X DELETE repos/${{ github.repository }}/git/refs/heads/${{ github.event.pull_request.head.ref }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
